ego_scan_topic: '/scan'
ego_odom_topic: '/odom'
ego_drive_topic: '/drive'
opp_scan_topic: '/opp_scan'
opp_odom_topic: '/opp_odom'
opp_drive_topic: '/opp_drive'


lap_count_topic: '/lap_count'
lap_time_topic: '/lap_time'
collision_topic: '/collision'

race_info_topic: '/race_info'

# fixed vals DO NOT CHANGE
scan_fov: 4.7
scan_beams: 1080
scan_distance_to_base_link: 0.275

map_path: '/f1tenth_gym/maps/skirk.yaml'
map_img_ext: '.png'
executable_dir: '/f1tenth_gym/build/'

waypoints_path: '/catkin_ws/src/f1tenth_gym_ros/maps/skirk.csv'